services:
  - type: web
    name: wppconnect-server
    env: node
    plan: free
    buildCommand: |
      npm install
      npx puppeteer install chrome
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/.local-chromium/linux-1220945/chrome-linux/chrome
      - key: CHROMIUM_ARGS
        value: "--no-sandbox --disable-setuid-sandbox"
